project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("table_booker.urls")),
    path("admin/", admin.site.urls),
]

table_booker/urls.py
from django.urls import path

from . import views

app_name = "table_booker"

urlpatterns = [
    path("", views.home_page, name="home"),
    path("login", views.login_page, name="login"),
    path("logout", views.logout_page, name="logout"),
    path("signup", views.signup_page, name="signup"),
    path(
        "book-restaurant/<int:restaurant_id>",
        views.book_restaurant,
        name="book-restaurant",
    ),
    path("my-bookings", views.my_bookings, name="my-bookings"),
    path(
        "delete-booking/<int:booking_id>", views.delete_booking, name="delete-booking"
    ),
    path(
        "update-booking/<int:booking_id>", views.update_booking, name="update-booking"
    ),
]

table_booker/models.py
from django.contrib.auth.models import User
from django.db import models


class Restaurant(models.Model):
    name = models.CharField(max_length=150)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250)
    postcode = models.CharField(max_length=12)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


class Table(models.Model):
    restaurant = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, related_name="tables"
    )
    name = models.CharField(max_length=250)
    capacity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} capacity: {self.capacity}"


class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    date = models.DateTimeField()
    total_guests = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


DAYS_OF_WEEK = (
    (0, "Monday"),
    (1, "Tuesday"),
    (2, "Wednesday"),
    (3, "Thursday"),
    (4, "Friday"),
    (5, "Saturday"),
    (6, "Sunday"),
)


class BusinessHour(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    day = models.IntegerField(choices=DAYS_OF_WEEK)
    start_time = models.TimeField()
    finish_time = models.TimeField()
    closed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


class Setting(models.Model):
    restaurant = models.OneToOneField(
        Restaurant, on_delete=models.CASCADE, related_name="setting"
    )
    min_guest = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

table_booker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import Booking, Table


class UserForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class BookingForm(forms.ModelForm):
    date = forms.DateTimeField(
        input_formats=["%Y-%m-%dT%H:%M"],
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local", "class": "form-control"},
            format="%Y-%m-%dT%H:%M",
        ),
    )

    def __init__(self, restaurant, *args, **kwargs):
        super(BookingForm, self).__init__(*args, **kwargs)
        self.fields["table"].queryset = Table.objects.filter(
            restaurant_id=restaurant.id
        )
        self.restaurant = restaurant

    class Meta:
        model = Booking
        fields = ("table", "date", "total_guests")

    def clean(self):
        cleaned_data = super().clean()
        date = cleaned_data.get("date")
        total_guests = cleaned_data.get("total_guests")
        table = cleaned_data.get("table")
        min_guest = self.restaurant.setting.min_guest

        if total_guests is not None:
            if total_guests > table.capacity:
                raise ValidationError(
                    {"total_guests": [f"Maximum table capacity is {table.capacity}"]}
                )
            if total_guests < 1:
                raise ValidationError(
                    {"total_guests": ["Cannot book 0 or less guests"]}
                )

            if total_guests < min_guest:
                raise ValidationError(
                    {"total_guests": [f"Minimum guest bookable is: {min_guest}"]}
                )

        if date:
            if date < timezone.now():
                raise ValidationError({"date": ["Date cannot be in the past"]})

table_booker/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404, redirect, render

from .forms import BookingForm, UserForm
from .models import Booking, Restaurant


def home_page(request):
    if not request.user.is_authenticated:
        return redirect("table_booker:login")

    context = {"restaurants": Restaurant.objects.all()}
    return render(request, "home.html", context=context)


def book_restaurant(request, restaurant_id):
    if not request.user.is_authenticated:
        return redirect("table_booker:login")

    try:
        restaurant = Restaurant.objects.get(id=restaurant_id)
    except Restaurant.DoesNotExist:
        restaurant = None

    if restaurant is None:
        messages.error(request, "Invalid restaurant supplied")
        return redirect("table_booker:home")

    if request.method == "POST":
        form = BookingForm(restaurant, request.POST)

        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.restaurant = restaurant
            booking.save()
            messages.info(request, f"You successfully booked {restaurant.name}.")
            return redirect("table_booker:home")
    else:
        form = BookingForm(restaurant)

    return render(
        request=request,
        template_name="book_restaurant.html",
        context={"booking_form": form, "restaurant": restaurant},
    )


def delete_booking(request, booking_id):
    if not request.user.is_authenticated:
        return redirect("table_booker:login")

    booking = get_object_or_404(Booking, pk=booking_id)

    if request.method == "POST":
        booking.delete()
        return redirect("table_booker:my-bookings")

    return render(request, "delete_booking.html", context={"booking": booking})


def update_booking(request, booking_id):
    if not request.user.is_authenticated:
        return redirect("table_booker:login")

    booking = get_object_or_404(Booking, pk=booking_id)

    booking_form = {"booking_form": BookingForm(booking.restaurant, instance=booking)}

    if request.method == "POST":
        form = BookingForm(booking.restaurant, request.POST, instance=booking)

        if form.is_valid():
            form.save()
            messages.info(
                request, f"You successfully updated {booking.restaurant.name} booking"
            )
            return redirect("table_booker:my-bookings")

    return render(request, "update_booking.html", context=booking_form)


def my_bookings(request):
    if not request.user.is_authenticated:
        return redirect("table_booker:login")

    context = {"bookings": Booking.objects.filter(user=request.user)}
    return render(request, "my_bookings.html", context=context)


def login_page(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("table_booker:home")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(
        request=request, template_name="login.html", context={"login_form": form},
    )


def signup_page(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("table_booker:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = UserForm()
    return render(
        request=request, template_name="signup.html", context={"register_form": form},
    )


def logout_page(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("table_booker:login")

table_booker/templates/table_booker/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Table Booker</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'table_booker/css/main.css' %}">
</head>

<body>
  <div>
      <p id="message">{% include 'includes/messages.html' %}</p>
      <a href="/">Home</a> | {% if request.user.is_authenticated %}
      <a href="/my-bookings">My Bookings</a> | <a href="/logout">Logout</a> |
    {% else %}
      <a href="/signup">Signup</a>
    {% endif %} 
  </div>
  {% block content %} 
  {% endblock content %}
</body>

</html>

table_booker/templates/table_booker/book_restaurant.html
{% extends "base.html" %} 

{% block content %}
<section class="book-restaurant">
  <h1>Book Restaurant</h1>
  <h3>{{ restaurant.name }}</h3>
  <form method="POST">
    {% csrf_token %} {{ booking_form.as_p }}
    <button type="submit">Book Restaurant</button>
  </form>
  <p>Back to home page, <a href="/">home</a></p>
</section>
{% endblock content %}

table_booker/templates/table_booker/delete_booking.html
{% extends 'base.html' %}

{% block content %}
  <section class="delete-bookings">
    <h1>Delete Booking</h1>
    <p>Are you sure you want to delete:</p>
    <p>{{ booking.restaurant.name }}</p>
    <p>{{ booking.restaurant.table.name }}</p>
    <p>{{ booking.date }}</p>
    <form method="POST">
      {% csrf_token %}
      <button type="submit">YES, DELETE BOOKING</button>
    </form>
  </section>
{% endblock content %}

table_booker/templates/table_booker/home.html
{% extends "base.html" %}

{% block content %}
  <section class="home">
    <h1>HOME PAGE</h1>
    {% for restaurant in restaurants %}
      <p>
      {{ restaurant.name }}
      <a href="{% url 'table_booker:book-restaurant' restaurant.id%}">book restaurant</a>
      </p>
    {% empty %}
      <p>There are no records to show</p>
    {% endfor %} 
 </section>
{% endblock content %}

table_booker/templates/table_booker/login.html
{% extends "base.html" %} 

{% block content %}
  <section class="login">
    <h1>Login</h1>
    <form method="POST">
      {% csrf_token %} {{ login_form.as_p }}
      <button type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="/signup">Create an account</a>.</p>
  </section>
{% endblock content %}

table_booker/templates/table_booker/my_bookings.html
{% extends "base.html" %} 

{% block content %}
<section class="my-bookings">
  <h1>My Bookings</h1>
  <table border="1" cellpadding="10">
    <th>Restaurant</th>
    <th>Table</th>
    <th>Date</th>
    <th>Actions</th>
    {% for booking in bookings %}
    <tr>
      <td>{{ booking.restaurant.name }}</td>
      <td>{{ booking.table.name }}</td>
      <td>{{ booking.date }}</td>
      <td class="my-bookings__actions">
        <a href="/delete-booking/{{ booking.id }}">Delete</a> |
        <a href="/update-booking/{{ booking.id }}">Update Booking</a>
      </td>
    </tr>
    {% endfor %}
  </table>
</section>
{% endblock content %}

table_booker/templates/table_booker/signup.html
{% extends "base.html" %}

{% block content %}
  <section class="sign-up">
    <h1>Sign Up</h1>
    <form method="POST">
      {% csrf_token %}
      {{ register_form.as_p }}
      <button type="submit">Register</button>
    </form>
    <p>If you already have an account, <a href="/login">login</a> instead.</p>
  </section>
{% endblock content %}

table_booker/templates/table_booker/update_booking.html
{% extends 'base.html' %} 

{% block content %}
<section class="update-bookings">
  <h1>Update Booking</h1>
  <form method="POST">
    {% csrf_token %} {{ booking_form.as_p }}
    <button type="submit">Update Booking</button>
  </form>
</section>
{% endblock content %}